### PR TITLE
Update to latest beta version

### PR DESCRIPTION
**Pull request by derrickmehaffy**
Updating the api to latest strapi beta version because it was still on beta.0, lots of bug fixes since then

### CODE REVIEW

**Comment by lauriejim** [comment]
@derrickmehaffy Do you know about the travis error?

**Comment by derrickmehaffy** [comment]
Also we need to remove node 11 from Travis.

I'll update the PR shortly with some changes

**Comment by derrickmehaffy** [comment]
I'm not entirely sure what the purpose of the `xvfb` is here? And that appears to be the issue: 
```
The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .
```

**Comment by alexandrebodin** [comment]
@derrickmehaffy David fixed it in another PR you need to use dist: trusty

**Comment by derrickmehaffy** [comment]
Mmmmm this should be something that needs a more deep look into, testing on Ubuntu 14.04 really won't provide much considering it's EOL later on. 

image

**Comment by alexandrebodin** [comment]
@derrickmehaffy you can make the right update following this documentation :) https://www.google.com/search?q=travis+xvbf+xenial&rlz=1C5CHFA_enFR842FR842&oq=travis+xvbf+xenial&aqs=chrome..69i57j0.3172j0j1&sourceid=chrome&ie=UTF-8

**Comment by lauriejim** [comment]
I tested with last version and I made other function updates
See here: https://github.com/strapi/foodadvisor/pull/25
I think we have to marge the #25 PR instead of this one.

**Comment by alexandrebodin** [comment]
Closing this PR as it is outdated compared to https://github.com/strapi/foodadvisor/pull/26

**Pull request closed without merging**
