### PR TITLE
Upgrade: Strapi 4.13.5

### PR DESCRIPTION
**Pull request by Mcastres**

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]

**Review by derrickmehaffy — APPROVED** [review]
Did not run manual tests just approving in case it's needed.

**Comment by Mcastres** [comment]
I tested everything but I'll wait for Bart checks

**Comment by StrapiBartosh** [comment]
Tested on my end going through the items that I over on demos and everything looks good!

**Comment by derrickmehaffy** [comment]
Since bart reviewed I'll go ahead and merge to speed things along and not wait til monday

**Pull request merged**
