### PR TITLE
Chore: update the data.zip without any admin users created

### PR DESCRIPTION
**Pull request by Mcastres**
- Remove the already created admin users from the database

### CODE REVIEW

**Comment by ivanThePleasant** [comment]
I'm a bit confused by this one. So, you just cleared all admin users from the dump.sql in data.zip? That db seems to be empty, I checked. If that's the desired behavior, then all good I guess

**Comment by Mcastres** [comment]
Yes, this is what the database always looks like. Empty admin users but other CTs are there. You can actually hit the API to check (ex: /api/articles, /restaurants etc...)

**Comment by ivanThePleasant** [comment]
Yep, checked, seeding works ok, CTs are there, everything seems to work as intended 👍

**Comment by Mcastres** [comment]
Thank you very much @ivanThePleasant 🙏

**Pull request merged**
