### PR TITLE
Upgrade: Strapi version to 4.3.4

### PR DESCRIPTION
**Pull request by Mcastres**
- Upgrade to 4.3.6
- Add the agenda plugin
- Add the ER chart plugin
- Add the content-versioning plugin on the Global Single-Type only
- Updated the enum price for restaurants to avoid issues with GraphQL

### CODE REVIEW

**Comment by Java-Jive** [comment]
Hi @Mcastres, I just tried to upgrade to `v4.3.6` and when try to build it throws bunch of errors and your commit for `schema.json` and `admin.js` solves these errors, so thanks! But what is holding up this commit to merge?

**Comment by Mcastres** [comment]
Hello @Java-Jive 👋 
The merge will come soon :)

**Review by dennism501 — APPROVED** [review]
LGTM

**Review by dennism501 — APPROVED** [review]
LGTM

**Review by dennism501 — APPROVED** [review]

**Review by fdel-car — APPROVED** [review]

**Pull request merged**
